### PR TITLE
You couldn't cancel a verb that was called as an action, because it w…

### PR DESCRIPTION
**Pull request by santouits**
…as using its own ip variable and not the verb's

### CODE REVIEW

**Comment by bladecoder** [comment]
Hi!

What is the use case for this?

You can cancel a verb running by the RunVerbAction cancelling the parent verb. Using an ip in the RunVerbAction allows to call a Verb in parallel from several other verbs.

**Comment by santouits** [comment]
hello, well you are right, I didn't think about that. In my case I was having a verb that was run in the init function and has a character patroling around with repeat action. But if you talk to that character while he is moving, the verb breaks, so I was running it again at the end of the talk to verb. I could just have a new verb to cancel init and talk verbs if they are running. ok thank you.

**Comment by bladecoder** [comment]
Yes, you can cancel ```init```. I don't see why not...

**Comment by santouits** [comment]
alright, I close this as it is not a bug, but an expected behaviour

**Pull request closed without merging**
